name: Cybersecurity Chatbot CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '6.0.x'
  BUILD_CONFIG: 'Release'

jobs:
  validate-environment:
    name: Validate Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verify Project Structure
        run: |
          if [ ! -f *.csproj ]; then
            echo "::error::No .csproj file found in root directory"
            exit 1
          fi
          echo "Project structure OK"

  build-and-test:
    name: Build and Test
    needs: validate-environment
    runs-on: windows-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Packages (with retry)
        run: |
          $retryCount = 0
          $maxRetries = 3
          do {
            try {
              dotnet restore
              break
            } catch {
              $retryCount++
              if ($retryCount -ge $maxRetries) { exit 1 }
              Start-Sleep -Seconds 5
            }
          } while ($true)
        shell: pwsh

      - name: Build Solution
        run: dotnet build --configuration ${{ env.BUILD_CONFIG }} --no-restore -p:Platform="x64"

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

      - name: Check Audio Compatibility
        if: runner.os != 'Windows'
        run: |
          echo "::warning::SoundPlayer only works on Windows. Audio features will be disabled."
          # Add your cross-platform fallback here

  deploy:
    name: Deploy Executable
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish Single File
        run: |
          dotnet publish -c ${{ env.BUILD_CONFIG }} -r win-x64 \
          --self-contained true \
          -p:PublishSingleFile=true \
          -p:IncludeNativeLibrariesForSelfExtract=true \
          -o ./publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: chatbot-executable
          path: ./publish
          retention-days: 3
